name: Rust Audit

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch: {}

env:
  CARGO_TERM_COLOR: always

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v1
    - run: cargo install cargo-audit
    - run: cargo audit
